// カードデータ - rule_v2.md (Ver 2.3+) に準拠
const cardsData = [
    // === 文化カード (緑) - 知識(K) ===
    {
        id: 1,
        name_jp: "燐字の光",
        name_original: "linman leti kapa",
        type: "culture",
        level: 1,
        count: 5,
        move: 1,
        move_resource: [],
        cost: { K: 2 },
        production_condition: 'K',
        production: { K: 1 },
        vp_logic: "static",
        vp: 0,
        image_src: "../cards_new/cards_1 ページ.png"
    },
    {
        id: 2,
        name_jp: "アイルのパンとアイルの芋",
        name_original: "ail onec at ail dectok",
        type: "culture",
        level: 1,
        count: 5,
        move: 1,
        move_resource: [],
        cost: { K: 1, F: 2 },
        production_condition: 'K',
        production: { F: 1 },
        vp_logic: "static",
        vp: 1,
        chain_build: 1,
        image_src: "../cards_new/cards_2 ページ.png"
    },
    {
        id: 3,
        name_jp: "他国の書物",
        name_original: "etleti icco leti kulante",
        type: "culture",
        level: 2,
        count: 4,
        move: 2,
        move_resource: [],
        cost: { K: 3 },
        production_condition: 'K',
        production: { K: 2 },
        vp_logic: "static",
        vp: 2,
        image_src: "../cards_new/cards_3 ページ.png"
    },
    {
        id: 4,
        name_jp: "アイル標準机戦",
        name_original: "ail panit leti cetkaik",
        type: "culture",
        level: 3,
        count: 2,
        move: 1,
        move_resource: ["K"],
        cost: { K: 2, F: 2 },
        production_condition: 'K',
        production: { M: "variable" },
        vp_logic: "static",
        vp: 3,
        production_logic: "variable",
        production_formula: "count(culture_cards)",
        production_resource: "M",
        image_src: "../cards_new/cards_4 ページ.png"
    },

    // === 産業カード (紫) - 資材(M) ===
    {
        id: 5,
        name_jp: "資源の採掘",
        name_original: "letit kile inimoc",
        type: "industry",
        level: 1,
        count: 5,
        move: 0,
        move_resource: [],
        cost: { M: 2 },
        production_condition: 'M',
        production: { M: 1 },
        vp_logic: "static",
        vp: 0,
        chain_build: 1,
        image_src: "../cards_new/cards_5 ページ.png"
    },
    {
        id: 6,
        name_jp: "ナナラ港",
        name_original: "nanala junalika",
        type: "industry",
        level: 1,
        count: 5,
        move: 3,
        move_resource: [],
        cost: { M: 1, K: 2 },
        production_condition: 'M',
        production: { K: 1 },
        vp_logic: "static",
        vp: 1,
        chain_build: 1,
        image_src: "../cards_new/cards_6 ページ.png"
    },
    {
        id: 7,
        name_jp: "機械油の力",
        name_original: "ben leti anpe",
        type: "industry",
        level: 2,
        count: 4,
        move: 2,
        move_resource: [],
        cost: { M: 3 },
        production_condition: 'M',
        production: { M: 2 },
        vp_logic: "static",
        vp: 2,
        image_src: "../cards_new/cards_7 ページ.png"
    },
    {
        id: 8,
        name_jp: "シェプオキヤウの大経済",
        name_original: "xep okijau leti xep kukol",
        type: "industry",
        level: 3,
        count: 2,
        move: 3,
        move_resource: ["M"],
        cost: { M: 2, K: 2 },
        production_condition: 'M',
        production: { F: "variable" },
        vp_logic: "static",
        vp: 3,
        production_logic: "variable",
        production_formula: "count(industry_cards)",
        production_resource: "F",
        image_src: "../cards_new/cards_8 ページ.png"
    },

    // === 政治カード (橙) - 食糧(F) ===
    {
        id: 9,
        name_jp: "法改正",
        name_original: "dutucunit cepkulante",
        type: "politics",
        level: 1,
        count: 5,
        move: 1,
        move_resource: [],
        cost: { F: 2 },
        production_condition: 'F',
        production: { F: 1 },
        vp_logic: "static",
        vp: 0,
        image_src: "../cards_new/cards_9 ページ.png"
    },
    {
        id: 10,
        name_jp: "敵などいないアイル兵",
        name_original: "zik molip leti ail elme",
        type: "politics",
        level: 1,
        count: 5,
        move: 2,
        move_resource: [],
        cost: { F: 1, M: 2 },
        production_condition: 'F',
        production: { M: 1 },
        vp_logic: "none",
        vp: 0,
        draw_extra: 1,
        image_src: "../cards_new/cards_10 ページ.png"
    },
    {
        id: 11,
        name_jp: "アイル国民の力",
        name_original: "ail lata leti anpe",
        type: "politics",
        level: 2,
        count: 4,
        move: 1,
        move_resource: [],
        cost: { F: 3 },
        production_condition: 'F',
        production: { F: 2 },
        vp_logic: "static",
        vp: 2,
        draw_extra: 1,
        image_src: "../cards_new/cards_11 ページ.png"
    },
    {
        id: 12,
        name_jp: "10月8日",
        name_original: "ana leti lekka",
        type: "politics",
        level: 3,
        count: 2,
        move: 2,
        move_resource: ["F"],
        cost: { F: 2, M: 2 },
        production_condition: "F",
        production: { K: "variable" },
        vp_logic: "static",
        vp: 3,
        production_logic: "variable",
        production_formula: "count(politics_cards)",
        production_resource: "K",
        image_src: "../cards_new/cards_12 ページ.png"
    },

    // === 無色・特殊カード (白) ===
    // ID 13 (投資) は rule_v2.md から削除されたため除外

    {
        id: 14,
        name_jp: "旅",
        name_original: "xuwelic",
        type: "colorless",
        level: null,
        count: 4,
        move: 2,
        move_resource: ["K", "M", "F"],
        cost: { multi: "same4" },
        effect: "convert_same3_to_W",
        vp: 0,
        chain_build: 1,
        image_src: "../cards_new/cards_14 ページ.png"
    },

    // === 変動VPカード (得点源) ===
    {
        id: 15,
        name_jp: "良き文化",
        name_original: "pankaleti mo",
        type: "colorless",
        level: null,
        count: 2,
        move: 3,
        move_resource: ["K", "M", "F"],
        cost: { K: 3, F: 3 },
        vp_logic: "variable",
        vp_text: "2 x 文化",
        vp_formula: "2 * count(culture_cards)",
        image_src: "../cards_new/cards_15 ページ.png"
    },
    {
        id: 16,
        name_jp: "古きを思い新しきに行く",
        name_original: "ticotit penulleti pi tude jo dutucunleti",
        type: "colorless",
        level: null,
        count: 2,
        move: 3,
        move_resource: ["K", "M", "F"],
        cost: { M: 3, K: 3 },
        vp_logic: "variable",
        vp_text: "2 x 産業",
        vp_formula: "2 * count(industry_cards)",
        image_src: "../cards_new/cards_16 ページ.png"
    },
    {
        id: 17,
        name_jp: "筆兵無傾",
        name_original: "kuwa at elme",
        type: "colorless",
        level: null,
        count: 2,
        move: 3,
        move_resource: ["K", "M", "F"],
        cost: { F: 3, M: 3 },
        vp_logic: "variable",
        vp_text: "2 x 政治",
        vp_formula: "2 * count(politics_cards)",
        image_src: "../cards_new/cards_17 ページ.png"
    },
    {
        id: 18,
        name_jp: "アイルの道",
        name_original: "ail lime",
        type: "colorless",
        level: null,
        count: 1,
        move: 3,
        move_resource: ["K", "M", "F"],
        cost: { F: 2, K: 2, M: 2 },
        vp_logic: "variable",
        vp_formula: "2 * count(round_tokens)",
        vp_text: "Wトークン x2",
        image_src: "../cards_new/cards_18 ページ.png"
    },
    {
        id: 19,
        name_jp: "アイル共和国憲法",
        name_original: "ail xep cepkulante",
        type: "colorless",
        level: null,
        count: 1,
        move: 3,
        move_resource: ["K", "M", "F"],
        cost: { F: 2, K: 2, M: 2 },
        vp_logic: "variable",
        vp_formula: "3 * min(culture, industry, politics)",
        vp_text: "文化産業政治セット x3",
        image_src: "../cards_new/cards_19 ページ.png"
    }
];

const cardBackImage = "../cards_new/cards_20 ページ.png";

if (typeof module !== 'undefined') module.exports = cardsData;
